# Generated by Django 3.2.7 on 2022-04-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('fname', models.CharField(default='', max_length=1000)),
                ('lname', models.CharField(default='', max_length=1000)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=1000)),
                ('fname', models.CharField(default='', max_length=1000)),
                ('lname', models.CharField(default='', max_length=1000)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='events/')),
            ],
        ),
    ]
